steps:
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gameoflife:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/gameoflife:latest", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/gameoflife:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/gameoflife:latest"]
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg'
  - 'SONARQUBE_SCANNER_CLI_VERSION=3.2.0.1227'
  - '-t'
  - 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/sonar-scanner:3.2.0.1227'
  - '.'
images: 
- 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
- 'gcr.io/$PROJECT_ID/sonar-scanner:3.2.0.1227'

- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args:
  - 'sonar:sonar'
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.login=3502bd1b7a0cc9d8679c51b63c1003f4458e22ea'
  dir: .
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/gameoflife:latest
  - --location=us-central1-a
  - --cluster=standard-cluster-2
  - --app=gameoflife
  - --expose=8080
  - --namespace=default
options:
    machineType: 'N1_HIGHCPU_8'
